eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

name:
  value: nebrass

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sleuth:
    sampler:
      probability: 1
  h2:
    console:
      enabled: true

logstash:
  host: localhost
  port: 5000
  queue-size: 512

management:
  endpoints:
    web:
      exposure:
        include: "*"